apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-lightblue-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: pod-mysql
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: "registry.ng.bluemix.net/<namespace>/mysql"
          imagePullPolicy: Always
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 20
            periodSeconds: 60
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: "replace_with_mysql_root_passoword"
          - name: MYSQL_USER
            value: "replace_with_mysql_user"
          - name: MYSQL_PASSWORD
            value: "replace_with_mysql_password"
          - name: MYSQL_DATABASE
            value: "inventorydb"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-lightblue-service
  labels:
    app: mysql
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
   - protocol: TCP
     port: 3306
     nodePort: 30006
